Login Logout
MiraVV/nodejs-homework-rest-api pull request #3
Opened 2022-12-20 20:38 UTC by MiraVV

2022-12-21 07:46 UTC, BohdanGres requested changes

2022-12-21 07:46 UTC, BohdanGres commented on middlewares/auth.js
> +    if (!user || !user.token) {
тут ще треба перевірити чи user.token === token

2022-12-21 07:46 UTC, BohdanGres commented on app.js
>  app.use("/api/contacts", contactsRouter);
на цей роут можеш одразу навісити мідлварку для перевірки токена

2022-12-21 20:38 UTC, MiraVV commented on middlewares/auth.js
> +    if (!user || !user.token) {
done

2022-12-21 20:39 UTC, MiraVV commented on app.js
>  app.use("/api/contacts", contactsRouter);
done

2022-12-22 20:05 UTC, BohdanGres approved these changes

2022-12-22 22:20 UTC, merged